- frontend/.eslintrc.cjs
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/index.css
- frontend/src/routes/ProtectedRoutes.tsx
- frontend/src/routes/PublicOnlyRoutes.tsx
- frontend/src/routes/Routes.tsx
- frontend/tailwind.config.js
- Instalação do `react-router-dom` Seguindo a [documentação](https://reactrouter.com/en/main/start/tutorial)
- Componentes: PublicOnlyRoutes, ProtectedRoutes e Routes
- Implementação no `App.tsx`
> Criação das rotas no front end

- .devcontainer/devcontainer.json
- frontend/src/components/layout/Content.tsx
- frontend/src/components/layout/Header.tsx
- frontend/src/components/ui/Card.tsx
- frontend/src/index.css
- frontend/src/pages/Home.tsx
- frontend/src/routes/ProtectedRoutes.tsx
- frontend/src/routes/PublicOnlyRoutes.tsx
- frontend/src/routes/Routes.tsx
- Remoção de `export default` nas rotas
- Configuração de indentação
- Adição de variáveis globais no css
- Criação do componente `Card`
- Criação do componente `Content`
- `Content.Root`: Responsável pelo grid de 3 colunas + responsividade
- `Content.Sidebar`: Containers laterais
- `Content.Main`: Container central
> Criação do Layout da Home

- frontend/src/models/Category.ts
- frontend/src/models/Comment.ts
- frontend/src/models/Post.ts
- frontend/src/models/Tag.ts
- frontend/src/models/User.ts
- frontend/src/models/Vote.ts
- Category
- Comment
- Post
- Tag
- User
- Vote
> Wip: Criar tipagem das entidades no front end 

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/shared/PostCard.tsx
- frontend/src/components/ui/SmallTabs.tsx
- frontend/src/components/ui/Tag.tsx
- frontend/src/examples/mocks/mocks.ts
- frontend/src/pages/Home.tsx
(Adicione em itens as mudanças contidas neste Pull Request)
- PostCard
- Instalação do `react-markdown` (Precisa rodar `make install`)
- Criação das SmallTabs
> Criação dos componentes da Home

- frontend/src/components/form/SmartField/types/index.ts
- frontend/src/components/form/SmartForm/utils/getValidator.ts
- frontend/src/components/form/SmartForm/utils/validateField.ts
- frontend/src/components/layout/Layout.tsx
- frontend/src/components/layout/PublicBackground.tsx
- frontend/src/pages/Login.tsx
- frontend/src/pages/Signup.tsx
- frontend/src/routes/Routes.tsx
- Criação da interface de signup
- Criação de novas regras de validação
- Criação da PublicBackground 
> Signup layout

- .devcontainer/docker-compose.yml
- .devcontainer/nginx/config/default.conf
- backend/composer.json
- backend/composer.lock
- backend/src/DI/Slim.php
- backend/src/Service/MailerService.php
- backend/src/Service/UserService.php
- backend/src/swagger.yaml
- Adicionado MailerService
- Adicionado PHPMailer
- Adicionado email de boas vindas
> feat: Implemented MailerService and welcome email

- backend/src/Controller/UserController.php
- backend/src/Service/UserService.php
- frontend/src/components/form/SmartForm/hooks/useSmartForm.ts
- frontend/src/components/form/SmartForm/index.tsx
- frontend/src/components/layout/Header.tsx
- frontend/src/containers/SignupForm.tsx
- frontend/src/pages/Signup.tsx
- frontend/src/services/userService.ts
- frontend/src/utils/dataURLToBlob.ts
- frontend/src/utils/printFirstAndLastName.ts
- Add signup no userService
- Correção de bug de upload de avatar no backend
- função dataURLToBlob
- printFirstAndLastName
Sem preview de signup pois manteve o que já existia
Usuário logado:
> Cadastro de usuário conectado com back end

- backend/src/Domain/Category.php
- backend/src/Domain/Comment.php
- backend/src/Domain/Post.php
- backend/src/Domain/Tag.php
- backend/src/Domain/Vote.php
- Criação de classes para banco de dados
> feat: Database structure done

- frontend/src/components/form/SmartField/index.tsx
- Desabilita o input quando há um arquivo
> Correção do bug fazer upload de avatar

- frontend/src/components/form/FileInput.tsx
- Add type="button" no preview de imagem
https://github.com/user-attachments/assets/7f9d17a5-c813-42cc-ae0d-4bd7cb9d98dd
https://github.com/user-attachments/assets/4fa70018-a0bf-4063-b01e-363e981238c9
> Correção do bug no FileInput ao apertar Enter 

- frontend/src/components/layout/Header.tsx
- frontend/src/pages/Search.tsx
- frontend/src/routes/Routes.tsx
- Inclusão do Search no Header
- Criação da funcionalidade que leva as informações de pesquisa para a URL.
> Seach-screen

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/form/TextEditor.tsx
- frontend/src/components/layout/Header.tsx
- frontend/src/components/ui/GoBack.tsx
- frontend/src/components/ui/Heading.tsx
- frontend/src/containers/NewOrEditPost/components/NewPostDetailsCard.tsx
- frontend/src/containers/NewOrEditPost/components/NewPostEditor.tsx
- frontend/src/containers/NewOrEditPost/constants/postFields.ts
- frontend/src/containers/NewOrEditPost/contexts/NewPostContext.tsx
- frontend/src/containers/NewOrEditPost/hooks/useNewPost.ts
- frontend/src/pages/NewPost.tsx
⚠A pasta `containers` será utilizada para conter a complexidade das páginas. Em vez de criar lógicas na pasta page, crie uma pasta nos containers e você poderá criar componentes, hooks, constantes, contexts e depois importar na page.
- Instalação do `lodash` para funções auxiliares
- Na pasta `containers`, eu criei uma subpasta chamada `NewOrEditPost`, essa pasta irá conter os componentes e as lógicas compartilhadas entre criação e ediçao de posts.
- NewPostContext: 
- Gerencia o `useSmartForm` e disponibiliza os estados pra baixo. 
- Lida com o salvamento de rascunho no localStorage
- NewPostDetailsCard: pequeno form na direita com os detalhes do post
- NewPostEditor: editor de texto já linkado com o estado do formulário
- Ajustes em componentes existentes. …
> Criação de post

- frontend/src/components/form/SmartForm/hooks/useSmartForm.ts
- frontend/src/components/ui/Button.tsx
- frontend/src/components/ui/ContentSkeleton.tsx
- frontend/src/constants/toastMessages.ts
- frontend/src/containers/NewOrEditPost/components/DeletePostCard.tsx
- frontend/src/containers/NewOrEditPost/components/EditPostDetailsCard.tsx
- frontend/src/containers/NewOrEditPost/components/EditPostEditor.tsx
- frontend/src/containers/NewOrEditPost/constants/postFields.ts
- frontend/src/containers/NewOrEditPost/contexts/EditPostContext.tsx
- frontend/src/containers/NewOrEditPost/hooks/useEditPost.ts
- frontend/src/examples/mocks/mocks.ts
- frontend/src/pages/EditPost.tsx
- frontend/src/routes/Routes.tsx
- frontend/src/services/postService.ts
(Adicione em itens as mudanças contidas neste Pull Request)
- Ajuste no useSmartForm
- Criação de Skeleton
- DeletePost Card
- postService mockado
- EditPostContext + componentes similares á criação de Post
> Tela de edição de post

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/layout/Header.tsx
- frontend/src/components/ui/AlertDialog.tsx
- frontend/src/components/ui/Button.tsx
- Criação de funcionalidade de logout
- Criação do componente AlertDialog
> Criação de funcionalidade de logout

- Makefile
- backend/bin/seed
- backend/composer.json
- backend/src/Command/DatabaseSeeder.php
- Adicionado comando para inicializar as categorias no banco de dados
> Seed de categorias 

- .github/workflows/lint.yml
- Ao rodar uma nova pipeline o linter verifica se há problemas no código
> Adiciona linter nas actions do Github

- frontend/src/components/ui/AlertDialog.tsx
- frontend/src/constants/toastMessages.ts
- frontend/src/containers/NewOrEditPost/components/DeletePostCard.tsx
- frontend/src/containers/NewOrEditPost/contexts/EditPostContext.tsx
- frontend/src/containers/NewOrEditPost/contexts/NewPostContext.tsx
- frontend/src/services/postService.ts
(Adicione em itens as mudanças contidas neste Pull Request)
- Implementação dos serviços `update` e `delete` no postService
- Ajustes necessários no NewPostContext e EditPostContext
- Implementação do delete no DeletePostCard
> Edição e deleção de posts

- frontend/src/components/layout/Header.tsx
- Correção do bug de retorno da página para origem
> fix: searchParms bug

- frontend/src/components/shared/PostCard.tsx
- frontend/src/containers/HomeContent.tsx
- frontend/src/containers/NewOrEditPost/components/DeletePostCard.tsx
- frontend/src/containers/NewOrEditPost/contexts/EditPostContext.tsx
- frontend/src/containers/NewOrEditPost/contexts/NewPostContext.tsx
- frontend/src/contexts/ResourceContext.tsx
- frontend/src/hooks/resources/usePaginatedResource.ts
- frontend/src/hooks/useCache.ts
- frontend/src/models/IPaginatedResource.ts
- frontend/src/utils/isDateExpired.ts
- Abstração da lógica de cache para dentro do `useCache`
- Função helper `isDateExpired` para saber se uma data já passou da validade, de acordo com o tempo de expiração
- Lógica de paginação no HomeContent
- Adjustment on PostCard content characters limit
> Lógica de paginação

- frontend/src/contexts/AuthContext.tsx
- Inclui interceptors para deslogar o usuário quando recebe status 401. 
- ⚠Se adicionamos roles ou permissões só devemos alterar para deslogar SOMENTE SE o token está inválido ou expirado.
> Intercepta requests não autorizadas

- .github/workflows/sonarqube.yml
- Configuração do projeto no SonarQube
- Criação do workflow de portão de qualidade para PRs no front end
> Adição do sonarqube

- frontend/src/components/form/TextEditor.tsx
- frontend/src/components/shared/CommentCard.tsx
- frontend/src/components/shared/CommentEditor.tsx
- frontend/src/components/shared/PostCard.tsx
- frontend/src/components/ui/Card.tsx
- frontend/src/containers/NewOrEditPost/components/PostEditor.tsx
- frontend/src/containers/PostComments.tsx
- frontend/src/containers/PostContent.tsx
- frontend/src/hooks/shared/useCommentManager.ts
- frontend/src/pages/PostPage.tsx
- frontend/src/services/commentService.ts
- CommentEditor
- commentService mockado
https://github.com/user-attachments/assets/4f2e6b43-61b8-419a-abae-895f2de38737
> Layout de criação de comentários

- .github/workflows/sonarqube.yml
> Trigger sonar only for pull requests

- backend/src/Controller/CommentController.php
- backend/src/Controller/PostController.php
- backend/src/Controller/UserController.php
- backend/src/DI/Slim.php
- backend/src/DTO/CommentDTO.php
- backend/src/Domain/Comment.php
- backend/src/Middleware/AuthMiddleware.php
- backend/src/Repository/CommentRepository.php
- backend/src/Repository/PostRepository.php
- backend/src/Service/CommentService.php
- backend/src/routes.php
- backend/src/swagger.yaml
- Melhoria no parametro userId no AuthMiddleware
- Criação das rotas, metodos em serviço e repositório para a manutenção de comentarios
> Backend Comentarios

- backend/src/Controller/UserController.php
- backend/src/DTO/UserInfoUpdateDTO.php
- backend/src/DTO/UserUpdateDTO.php
- backend/src/Repository/UserRepository.php
- backend/src/Service/UserService.php
- backend/src/routes.php
- backend/src/swagger.yaml
- Criação do fluxo de updateUser (DTO, service, controller...)
- Swagger implementado
https://github.com/user-attachments/assets/b49a8e27-0813-41c9-bd88-65c79230e986
> Update de usuário

- backend/src/Controller/CategoryController.php
- backend/src/Repository/CategoryRepository.php
- backend/src/Service/CategoryService.php
- backend/src/routes.php
- backend/src/swagger.yaml
- frontend/src/components/shared/GlobalSidebar.tsx
- frontend/src/contexts/ResourceContext.tsx
- frontend/src/hooks/resources/useGenericResource.ts
- frontend/src/models/IGenericResource.ts
- frontend/src/services/categoryService.ts
- Criação de fluxo de categorias populares no back end: `/categories/trending`
- Criação do `useGenericResource` que aceita qualquer tipo de chamada ao backend
- Listagem de popular categories no front
https://github.com/user-attachments/assets/e7358521-3875-4694-a116-0e85cde60c82
> Categorias populares

- backend/src/Controller/TagController.php
- backend/src/Domain/Tag.php
- backend/src/Repository/TagRepository.php
- backend/src/Service/TagService.php
- backend/src/routes.php
- backend/src/swagger.yaml
- frontend/src/components/shared/GlobalSidebar.tsx
- frontend/src/contexts/ResourceContext.tsx
- frontend/src/services/tagService.ts
- Trending tags back-end
- Listagem no front-end
> Tags populares

- backend/src/Controller/PostController.php
- backend/src/Domain/Post.php
- backend/src/Repository/CommentRepository.php
- backend/src/Repository/PostRepository.php
- backend/src/Service/PostService.php
- backend/src/routes.php
- backend/src/swagger.yaml
- frontend/src/components/shared/HeaderSearch.tsx
- frontend/src/components/shared/PostCard.tsx
- frontend/src/components/shared/PostList.tsx
- frontend/src/constants/post/index.ts
- frontend/src/containers/HomeContent.tsx
- frontend/src/containers/NewOrEditPost/components/DeletePostCard.tsx
- frontend/src/containers/NewOrEditPost/contexts/EditPostContext.tsx
- frontend/src/containers/NewOrEditPost/contexts/NewPostContext.tsx
- frontend/src/containers/PostContent.tsx
- frontend/src/containers/comments/PostComments.tsx
- frontend/src/containers/comments/components/CommentCard.tsx
- frontend/src/containers/comments/contexts/CommentsContext.tsx
- frontend/src/contexts/ResourceContext.tsx
- frontend/src/hooks/resources/useGenericResource.ts
- frontend/src/hooks/resources/usePaginatedResource.ts
- frontend/src/models/IGenericResource.ts
- frontend/src/models/Post.ts
- frontend/src/pages/PostPage.tsx
- frontend/src/pages/Search.tsx
- frontend/src/services/postService.ts
- frontend/src/utils/formatCompactNumber.ts
Ajustes para manter a UI e a API no mesmo caminho, ajustando pontos que existem apenas em um e não no outro
- Marcar comentário como favorito
- Trazer total de posts nos comentários
- Ajustes no front end (Responsividade + lógica)
- Ordenação e paginação consistentes
- Lógica de revalidação de dados atualizada com useRef e não com useState
> Sinconização entre front e back end

- frontend/src/components/shared/PostList.tsx
- frontend/src/components/ui/Tabs.tsx
- frontend/src/examples/mocks/mocks.ts
- frontend/src/pages/Profile.tsx
- frontend/src/pages/ProfileEdit.tsx
- frontend/src/pages/Rankings.tsx
- frontend/src/services/postService.ts
- Criação de Tabs seguindo o padrão do SmallTabs
> Feat: Criação de tabs para Ranking e Profile Edit

- backend/src/Controller/UserController.php
- backend/src/DI/Slim.php
- backend/src/Repository/CommentRepository.php
- backend/src/Repository/PostRepository.php
- backend/src/Repository/VoteRepository.php
- backend/src/Service/UserService.php
- backend/src/routes.php
- backend/src/swagger.yaml
- frontend/src/components/shared/ConnectedUserCard.tsx
- frontend/src/components/shared/UserCard.tsx
- frontend/src/components/shared/skeletons/UserCardSkeleton.tsx
- frontend/src/constants/post/index.ts
- frontend/src/contexts/ResourceContext.tsx
- frontend/src/hooks/resources/useGenericResource.ts
- frontend/src/models/IGenericResource.ts
- frontend/src/pages/Home.tsx
- frontend/src/pages/PostPage.tsx
- frontend/src/pages/Profile.tsx
- frontend/src/pages/ProfileEdit.tsx
- frontend/src/pages/Rankings.tsx
- frontend/src/services/userService.ts
- Rota `/user/overview/{id}`
- Componente UserCard + resource
> Overview do usuário

- backend/src/Controller/UserController.php
- backend/src/Domain/Comment.php
- backend/src/Domain/User.php
- backend/src/Repository/UserRepository.php
- backend/src/Service/UserService.php
- backend/src/routes.php
- backend/src/swagger.yaml
- frontend/src/components/form/FileInput.tsx
- frontend/src/components/shared/ConnectedRankingCard.tsx
- frontend/src/components/shared/PodiumList.tsx
- frontend/src/components/shared/RankingCard.tsx
- frontend/src/components/shared/UserCard.tsx
- frontend/src/components/ui/Pagination.tsx
- frontend/src/hooks/resources/useGenericResource.ts
- frontend/src/pages/Home.tsx
- frontend/src/pages/Profile.tsx
- frontend/src/pages/Rankings.tsx
- frontend/src/services/userService.ts
- Rota de ranking: `/user/ranking`
- userService e implementação
> Ranking de usuários

- .devcontainer/Dockerfile
- .devcontainer/docker-compose.yml
- .devcontainer/php/php.ini
- Makefile
- backend/bin/consume
- backend/composer.json
- backend/composer.lock
- backend/src/Command/EmailConsumer.php
- backend/src/Controller/CommentController.php
- backend/src/DTO/CommentDTO.php
- backend/src/Helper/QueueHelper.php
- backend/src/Service/CommentService.php
- backend/src/Service/MailerService.php
- Adição da infraestrura e configuração necessaria para o rabbitmq
- Correções php.ini
> Envio de email de comentario novo para o autor do post

- backend/src/Controller/PostController.php
- backend/src/Repository/PostRepository.php
- backend/src/Service/PostService.php
- backend/src/routes.php
- backend/src/swagger.yaml
- frontend/src/components/shared/DrawerMenu.tsx
- frontend/src/components/shared/TrendingPosts.tsx
- frontend/src/pages/Categories.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/PostPage.tsx
- frontend/src/pages/Profile.tsx
- frontend/src/pages/Search.tsx
- frontend/src/pages/Tags.tsx
- frontend/src/services/postService.ts
- Rota `/posts/trending`
- Integração no front end
> Funcionalidade de Trending Posts

- Makefile
Adiciona consumer no `make lazy`
> Correção Makefile

- backend/Dockerfile
- backend/index.php
- backend/info.php
- backend/php/php.ini
- backend/router.php
- backend/src/Middleware/CorsMiddleware.php
- backend/src/routes.php
- frontend/src/services/api.ts
- frontend/vercel.json
- Dockerfile para produção
- Ajustes de CORS
- info.php
- vercel.json
> Deploy na AWS + Vercel

- frontend/src/services/api.ts
> Api endpoint com load balancer https

- frontend/src/components/shared/Podium.tsx
- frontend/src/components/shared/TrendingPosts.tsx
- frontend/src/components/ui/Pagination.tsx
- frontend/src/containers/LoginForm.tsx
- frontend/src/pages/Rankings.tsx
- Remoção do Forgot password
- Ajuste Rankigs
- Ajustes de loadings
> Correções gerais

- backend/src/Service/UserService.php
- frontend/src/containers/NewOrEditPost/constants/postFields.ts
- frontend/src/containers/SignupForm.tsx
- frontend/src/containers/profile/UserInfoForm.tsx
- Tratamento de erros do backend
- Ajustes na edição de perfil
> Correção de bugs 

- .github/workflows/docker-deploy.yml
> Add docker-deploy

- .github/workflows/docker-deploy.yml
change task definition to receive arn
> Deploy AWS updated
